[config]
skip_core_tasks = true

[tasks.build]
script_runner = "@duckscript"
script = '''
cd user
exec cargo make build --release
cd ../os
exec cargo make build --release
'''

[tasks.qemu]
script_runner = "@duckscript"
script = '''
cd os
exec cargo dev-user
'''

[tasks.clean]
script_runner = "@duckscript"
script = '''
cd user 
exec cargo clean
cd ../os
exec cargo clean
'''

[tasks.clippy]
script_runner = "@duckscript"
script = '''
cd user 
exec cargo clippy --fix --allow-dirty
cd ../os
exec cargo clippy --fix --allow-dirty
'''

[tasks.fmt]
script_runner = "@duckscript"
script = '''
cd user 
exec cargo fmt
cd ../os
exec cargo fmt
'''

[tasks.tidy]
dependencies = ["clippy","fmt"]

[tasks.default]
script_runner = "@duckscript"
script = '''
echo exec `makers install-dependencies` to install dependencies automatically
echo note: you still need to install QEMU manually
echo exec `makers qemu` to run toyos
'''

[tasks.install-dependencies]
script_runner = "@duckscript"
script = '''
exec rustup toolchain add nightly
exec rustup component add llvm-tools-preview
exec rustup target add riscv64gc-unknown-none-elf
exec cargo install cargo-binutils
exec cargo install cargo-make
exec cargo install cargo-watch
'''
