[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tmisc/linker64.ld", "-Cforce-frame-pointers=yes"]
runner = "misc/runner.sh"
#runner = "qemu-system-riscv64 -machine virt -bios misc/rustsbi-qemu-no-log.bin -nographic -kernel"

[build]
target = "riscv64gc-unknown-none-elf"

