[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinker.ld", "-Cforce-frame-pointers=yes"]

[build]
target = "riscv64gc-unknown-none-elf"

[alias]
dev = "watch -c -q -- cargo make -l error run"